# Generated by Django 5.0.3 on 2024-03-25 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "posting_category",
                    models.CharField(
                        choices=[
                            ("sign_in", "Related Issue: Sign In"),
                            ("opinion_of_use", "Related Issue: Opinion of Use"),
                            ("error", "Related Issue: Some Error"),
                            ("improvements", "Related Issue: Improvements"),
                        ],
                        max_length=20,
                        verbose_name="Posting Category",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "disclosure_status",
                    models.BooleanField(default=True, verbose_name="Disclosure Status"),
                ),
                ("content", models.TextField(max_length=500, verbose_name="Content")),
                ("attachment", models.URLField(blank=True, verbose_name="Attachment")),
                ("hits", models.PositiveIntegerField(default=0, verbose_name="Hits")),
                (
                    "thumb_up_status",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Thumb-Up Status"
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posting",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Writer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(max_length=200, verbose_name="Comment")),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Writer",
                    ),
                ),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boards.posting",
                        verbose_name="Posting",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
